window.SAFARI_ANIMALS = [
  {
    id: "lion",
    name: "Lion",
    bingoName: "Lion",
    icon: "🦁",
    scientificName: "Panthera leo",
    type: "Big Five",
    region: "Serengeti and Ruaha",
    description:
      "Lions spend long periods resting, then suddenly switch into coordinated group hunting at dawn or dusk.",
    image: "/public/images/lion.jpg",
    source: "https://commons.wikimedia.org/wiki/File:African-lion.jpg",
  },
  {
    id: "leopard",
    name: "Leopard",
    bingoName: "Leopard",
    icon: "🐆",
    scientificName: "Panthera pardus",
    type: "Big Five",
    region: "Serengeti kopjes and riverine trees",
    description:
      "Leopards are solitary ambush hunters that often drag prey into trees to keep it away from scavengers.",
    image: "/public/images/leopard.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Leopard_(10829578893).jpg",
  },
  {
    id: "elephant",
    name: "African Elephant",
    bingoName: "Elephant",
    icon: "🐘",
    scientificName: "Loxodonta africana",
    type: "Big Five",
    region: "Tarangire and Serengeti plains",
    description:
      "Tanzania's elephants move in family groups led by experienced matriarchs and can travel far for water.",
    image: "/public/images/elephant.jpg",
    source:
      "https://commons.wikimedia.org/wiki/File:African_Elephant_(3076998686).jpg",
  },
  {
    id: "buffalo",
    name: "African Buffalo",
    bingoName: "Buffalo",
    icon: "🐃",
    scientificName: "Syncerus caffer",
    type: "Big Five",
    region: "Wet grasslands and woodland edges",
    description:
      "Buffalo are powerful herd animals with unpredictable moods, especially when calves are nearby.",
    image: "/public/images/buffalo.jpg",
    source: "https://commons.wikimedia.org/wiki/File:African_buffalo_(3).JPG",
  },
  {
    id: "rhino",
    name: "Black Rhinoceros",
    bingoName: "Rhino",
    icon: "🦏",
    scientificName: "Diceros bicornis",
    type: "Big Five",
    region: "Ngorongoro Conservation Area",
    description:
      "Black rhinos are browsers with pointed lips adapted for stripping leaves and twigs from shrubs.",
    image: "/public/images/rhino.jpg",
    source:
      "https://commons.wikimedia.org/wiki/File:Black_Rhinoceros_(52639155752).jpg",
  },
  {
    id: "cheetah",
    name: "Cheetah",
    bingoName: "Cheetah",
    icon: "🐆",
    scientificName: "Acinonyx jubatus",
    type: "Fast hunter",
    region: "Open grasslands",
    description:
      "Cheetahs rely on acceleration, balance, and sharp vision rather than brute strength to catch prey.",
    image: "/public/images/cheetah.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Cheetah_(3075280861).jpg",
  },
  {
    id: "giraffe",
    name: "Masai Giraffe",
    bingoName: "Giraffe",
    icon: "🦒",
    scientificName: "Giraffa tippelskirchi",
    type: "Towering browser",
    region: "Northern parks and acacia country",
    description:
      "Masai giraffes browse high branches with long prehensile tongues and move in loose, shifting groups.",
    image: "/public/images/giraffe.jpg",
    source:
      "https://commons.wikimedia.org/wiki/File:Masai_Giraffe_(7513600584).jpg",
  },
  {
    id: "zebra",
    name: "Plains Zebra",
    bingoName: "Zebra",
    icon: "🦓",
    scientificName: "Equus quagga",
    type: "Grazer",
    region: "Migration routes and short grass plains",
    description:
      "Every zebra has a unique stripe pattern, and herds use those patterns for recognition and defense.",
    image: "/public/images/zebra.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Plains_Zebra,_SA.JPG",
  },
  {
    id: "hippo",
    name: "Hippopotamus",
    bingoName: "Hippo",
    icon: "🦛",
    scientificName: "Hippopotamus amphibius",
    type: "River giant",
    region: "Rivers, pools, and floodplains",
    description:
      "Hippos spend much of the day cooling in water and leave the river at night to graze on land.",
    image: "/public/images/hippo.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Hippotamus.jpg",
  },
  {
    id: "wildebeest",
    name: "Blue Wildebeest",
    bingoName: "Wildebeest",
    icon: "🐂",
    scientificName: "Connochaetes taurinus",
    type: "Migration icon",
    region: "Serengeti migration corridor",
    description:
      "Wildebeest herds drive the Great Migration, following rain and fresh grass in immense seasonal loops.",
    image: "/public/images/wildebeest.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Wildebeest_(2404443933).jpg",
  },
  {
    id: "hyena",
    name: "Spotted Hyena",
    bingoName: "Hyena",
    icon: "🐾",
    scientificName: "Crocuta crocuta",
    type: "Scavenger and hunter",
    region: "Across most savanna habitats",
    description:
      "Spotted hyenas are highly social predators with strong jaws and complex clan hierarchies.",
    image: "/public/images/hyena.jpg",
    source:
      "https://commons.wikimedia.org/wiki/File:SPOTTED_HYENA_(10053466084).jpg",
  },
  {
    id: "warthog",
    name: "Warthog",
    bingoName: "Warthog",
    icon: "🐗",
    scientificName: "Phacochoerus africanus",
    type: "Savanna comic relief",
    region: "Short grass and open scrub",
    description:
      "Warthogs often sprint with their tails straight up and kneel on padded wrists while grazing.",
    image: "/public/images/warthog.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Fighting_warthog.JPG",
  },
  {
    id: "gazelle",
    name: "Thomson's Gazelle",
    bingoName: "Gazelle",
    icon: "🦌",
    scientificName: "Eudorcas thomsonii",
    type: "Plains sprinter",
    region: "Short grass plains",
    description:
      "These small antelope are alert, fast, and famous for explosive escape leaps called pronking.",
    image: "/public/images/gazelle.jpg",
    source:
      "https://commons.wikimedia.org/wiki/File:Thomson%27s_gazelle_(8455648344).jpg",
  },
  {
    id: "crocodile",
    name: "Nile Crocodile",
    bingoName: "Crocodile",
    icon: "🐊",
    scientificName: "Crocodylus niloticus",
    type: "River ambush predator",
    region: "Mara, Grumeti, and major rivers",
    description:
      "Nile crocodiles wait motionless near crossings, then explode forward with a powerful burst from the tail.",
    image: "/public/images/crocodile.jpg",
    source: "https://commons.wikimedia.org/wiki/File:A_Nile_Crocodile.jpg",
  },
  {
    id: "ostrich",
    name: "Common Ostrich",
    bingoName: "Ostrich",
    icon: "🐦",
    scientificName: "Struthio camelus",
    type: "Largest bird",
    region: "Open country and dry plains",
    description:
      "Ostriches cannot fly, but their long strides and speed make them hard to catch on open ground.",
    image: "/public/images/ostrich.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Common_ostrich.jpg",
  },
  {
    id: "baboon",
    name: "Olive Baboon",
    bingoName: "Baboon",
    icon: "🐒",
    scientificName: "Papio anubis",
    type: "Troop traveller",
    region: "Woodland edges and camps",
    description:
      "Olive baboons live in large troops and quickly learn where people or vehicles might leave food behind.",
    image: "/public/images/baboon.jpg",
    source:
      "https://commons.wikimedia.org/wiki/File:Olive_Baboon_(3075366181).jpg",
  },
  {
    id: "serval",
    name: "Serval",
    bingoName: "Serval",
    icon: "🐈",
    scientificName: "Leptailurus serval",
    type: "Secretive cat",
    region: "Tall grass and marshy flats",
    description:
      "The serval's oversized ears help it pinpoint rodents hidden under grass before making a vertical pounce.",
    image: "/public/images/serval.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Serval.jpg",
  },
  {
    id: "wild-dog",
    name: "African Wild Dog",
    bingoName: "Wild Dog",
    icon: "🐕",
    scientificName: "Lycaon pictus",
    type: "Pack hunter",
    region: "Rare but thrilling sighting",
    description:
      "Wild dogs hunt cooperatively with stamina and teamwork, covering huge distances in a single day.",
    image: "/public/images/wild-dog.jpg",
    source:
      "https://commons.wikimedia.org/wiki/File:African_wild_dog_(22640057727).jpg",
  },
  {
    id: "secretary-bird",
    name: "Secretary Bird",
    bingoName: "Bird",
    icon: "🦅",
    scientificName: "Sagittarius serpentarius",
    type: "Iconic raptor",
    region: "Open savanna",
    description:
      "This tall bird of prey walks the plains and uses rapid stamping kicks to subdue snakes and small animals.",
    image: "/public/images/secretary-bird.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Secretary_bird.jpg",
  },
  {
    id: "impala",
    name: "Impala",
    bingoName: "Impala",
    icon: "🦌",
    scientificName: "Aepyceros melampus",
    type: "Graceful antelope",
    region: "Woodland edges and mixed bush",
    description:
      "Impalas can leap long distances and often form alert herds that react quickly when predators appear.",
    image: "/public/images/impala.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Impala.jpg",
  },
  {
    id: "vervet-monkey",
    name: "Vervet Monkey",
    bingoName: "Monkey",
    icon: "🐒",
    scientificName: "Chlorocebus pygerythrus",
    type: "Alert primate",
    region: "Acacia groves and camp areas",
    description:
      "Vervet monkeys use distinct alarm calls for different predators and are quick to investigate human camps.",
    image: "/public/images/vervet-monkey.jpg",
    source:
      "https://commons.wikimedia.org/wiki/File:Vervet_monkey_(27536087342).jpg",
  },
  {
    id: "dik-dik",
    name: "Kirk's Dik-dik",
    bingoName: "Dik-dik",
    icon: "🦌",
    scientificName: "Madoqua kirkii",
    type: "Tiny browser",
    region: "Dense scrub and thorn bush",
    description:
      "Dik-diks are tiny antelope that freeze in cover and move in pairs through thick, dry vegetation.",
    image: "/public/images/dik-dik.jpg",
    source:
      "https://commons.wikimedia.org/wiki/File:Kirk%27s_Dik-Dik_(27638655543).jpg",
  },
  {
    id: "fish-eagle",
    name: "African Fish Eagle",
    bingoName: "Eagle",
    icon: "🦅",
    scientificName: "Icthyophaga vocifer",
    type: "Waterside raptor",
    region: "Lakeshores and river systems",
    description:
      "This powerful eagle is often heard before it is seen, calling from riverside trees before diving for fish.",
    image: "/public/images/fish-eagle.jpg",
    source: "https://commons.wikimedia.org/wiki/File:African_Fish_Eagle.jpg",
  },
  {
    id: "eland",
    name: "Common Eland",
    bingoName: "Eland",
    icon: "🦬",
    scientificName: "Taurotragus oryx",
    type: "Largest antelope",
    region: "Open woodland and plains",
    description:
      "Elands are massive but surprisingly nimble antelope that can clear high obstacles with light, springy jumps.",
    image: "/public/images/eland.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Common_Eland_(23).jpg",
  },
  {
    id: "hartebeest",
    name: "Coke's Hartebeest",
    bingoName: "Hartebeest",
    icon: "🦌",
    scientificName: "Alcelaphus buselaphus cokii",
    type: "Plain sentinel",
    region: "Open plains and short grass country",
    description:
      "Hartebeest often stand tall on the horizon, using keen eyesight and speed to detect and avoid danger.",
    image: "/public/images/hartebeest.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Coke%27s_Hartebeest.jpg",
  },
];
